### ISSUE TITLE
Tracks will be forwarded very fast

### ISSUE THREAD

**Issue by toyoman** [michaelherger/Spotty-Plugin#138] opened 2024-09-03 20:52 UTC
Hi Michael and others..
Our Kids love there Radios (Logitec Squeezebox Radio) and the server mostly works fine. But since today we have the issue (we had some months ago also):
You select some tracks, and they look like to play - but they forwarded in seconds to the next track. The Playlist is done.
Here are my versions (setup on PiCoreplayer with LMS Server):
Server: Version: 8.5.1 - 1713072758 @ Mon 15 Apr 2024 11:43:22 AM CEST
Betriebssystem: piCore - DE - utf8
Plattformarchitektur: aarch64-linux
Perl-Version: 5.36.0 - aarch64-linux-thread-multi
Audio::Scan: 1.09
IO::Socket::SSL: 2.083
Datenbankversion: DBD::SQLite 1.58 (sqlite 3.22.0)
Spotty Plugin:
Spotty 4.11.0
---
in the server log in debug mode, you can see all the tracks the server goes trough, but nothing will be played.
I also removed the Spotify Account, made a new Client ID (API) etc. nothing works.
Do you have an idea?
Thanks a lot. 
sascha

**Comment by toyoman** [comment] 2024-09-03 20:53
Additional from the server.log here are some entrys at last:
[24-09-03 22:52:50.5679] Plugins::Spotty::ProtocolHandler::getMetadataFor (190) Returning metadata cached in song object for spotify://track:3twzslV85VEnJNgjQtXoUW
[24-09-03 22:52:50.5687] Plugins::Spotty::ProtocolHandler::getMetadataFor (191) {
  album        => "Strictly 4 My N.I.G.G.A.Z...",
  artist       => "2Pac",
  bitrate      => "320k VBR",
  cover        => "https://i.scdn.co/image/ab67616d0000b2739f4932c81421643cd111a652",
  duration     => "118.478",
  icon         => "/html/images/cover.png",
  originalType => "Ogg Vorbis (Spotify)",
  title        => "Pac's Theme - Interlude",
  type         => "Ogg Vorbis (Spotify)",
  url          => "spotify://track:3twzslV85VEnJNgjQtXoUW",
}
[24-09-03 22:53:00.5657] Plugins::Spotty::ProtocolHandler::getMetadataFor (190) Returning metadata cached in song object for spotify://track:3twzslV85VEnJNgjQtXoUW
[24-09-03 22:53:00.5665] Plugins::Spotty::ProtocolHandler::getMetadataFor (191) {
  album        => "Strictly 4 My N.I.G.G.A.Z...",
  artist       => "2Pac",
  bitrate      => "320k VBR",
  cover        => "https://i.scdn.co/image/ab67616d0000b2739f4932c81421643cd111a652",
  duration     => "118.478",
  icon         => "/html/images/cover.png",
  originalType => "Ogg Vorbis (Spotify)",
  title        => "Pac's Theme - Interlude",
  type         => "Ogg Vorbis (Spotify)",
  url          => "spotify://track:3twzslV85VEnJNgjQtXoUW",
}
[24-09-03 22:53:00.5682] Plugins::Spotty::ProtocolHandler::getMetadataFor (190) Returning metadata cached in song object for spotify://track:3twzslV85VEnJNgjQtXoUW
[24-09-03 22:53:00.5690] Plugins::Spotty::ProtocolHandler::getMetadataFor (191) {
  album        => "Strictly 4 My N.I.G.G.A.Z...",
  artist       => "2Pac",
  bitrate      => "320k VBR",
  cover        => "https://i.scdn.co/image/ab67616d0000b2739f4932c81421643cd111a652",
  duration     => "118.478",
  icon         => "/html/images/cover.png",
  originalType => "Ogg Vorbis (Spotify)",
  title        => "Pac's Theme - Interlude",
  type         => "Ogg Vorbis (Spotify)",
  url          => "spotify://track:3twzslV85VEnJNgjQtXoUW",

**Comment by michaelherger** [comment] 2024-09-03 21:22
HI @toyoman 

Please see 
https://github.com/michaelherger/Spotty-Plugin/issues/137
https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1723569

I'm working on a fix. Thanks for your understanding.

Closing as dupe of #137

**Closed by michaelherger** 2024-09-03 21:22 UTC
