### ISSUE TITLE
Spotty stopped working

### ISSUE THREAD

**Issue by cregeland** [michaelherger/Spotty-Plugin#139] opened 2024-09-04 08:28 UTC
Hi, Spotty just stopped working after no issues for months. I have checked the client ID, logged in to Spotify Dev Platform. No issues with the API. Tried to restart the server and reinstalling the plugin.

Adding new user accounts work after reinstalling. Searching workings but when I try to play a track nothing happens. Same behaviour on multiple/all players. No problem with spotify app on iPhone.

Is there a logfile for the Spotty helper? I can’t seem to find any errors in the server log.

Thank you for your help:)

**Comment by michaelherger** [comment] 2024-09-04 08:41
dupe of #137

**Closed by michaelherger** 2024-09-04 08:41 UTC
