### ISSUE TITLE
Spotify Connect on second Account/Device wont work after setting Client ID

### ISSUE THREAD

**Issue by AgentT-mo** [michaelherger/Spotty-Plugin#38] opened 2021-06-04 15:38 UTC
#### Steps to reproduce 
1. Set Client ID with first Spotify Account
2. Connect to Spotty - Connect on a LMS Speaker with the Spotty Plugin with second Account (Girlfriend's Acc)
3. Spotify wont play

#### Current behaviour (bug)
No Music is playing on the Speaker, if you try to play using the second Account.
Only if you play it through the first Account with the Client ID.

#### Expected behaviour (correct)
Music should play on the Speaker with both Accounts.

#### Relevant logs and/or media (optional)
While playing with the first Account, no relevant log entries happen.
While trying to play with the second Account alot of these messages come up:
```
[21-06-04 16:02:58.8204] Plugins::Spotty::API::__ANON__ (1424) API call: me/player/devices
[21-06-04 16:02:58.8221] Plugins::Spotty::API::__ANON__ (1428) error: 403 Forbidden
```

#### Other comment (optional)
Without setting a Client ID, Spotify Connect works for multiple Accounts, but i get the ``` error: 429 unknown ```,
the playback sometimes randomly stops after songs.

Also when setting the Client ID every logged in Spotify Account in Spotty (on the Plugin Page at the Top)
change their name to the Spotify Account on which the Client ID was created.

**Comment by michaelherger** [comment] 2021-06-05 12:57
I've never seen this. Where did you enter the client ID? How does that look in the settings? We're using a family subscription with four accounts here.

**Comment by AgentT-mo** [comment] 2021-06-05 13:45
This is the Spotify Developer Page (I've hidden the middle part of the Client ID)
![Screenshot Spotify Developer](https://user-images.githubusercontent.com/10178218/120893598-6620c000-c614-11eb-9fb3-4a0992b05872.png)

This is the Spotty Plugin Settings Page in German Language.
I've also checked if there is a blank/space oder something after the Client ID, but there is just the ID.
![Screenshot Spotty Settings Page](https://user-images.githubusercontent.com/10178218/120893618-86507f00-c614-11eb-821a-ebf70352731b.png)

And a Screenshot of the Server Log
![Screenshot ServerLog](https://user-images.githubusercontent.com/10178218/120893637-9cf6d600-c614-11eb-8661-cbe0890102cf.png)
1) I started with a fresh restart of the LMS Server
2) I started Playing with Spotify connect. It worked (but got this error)
Afterwards i stopped and disconnected from the Speaker in the Spotify App.
3) 2nd Account connected to the Speaker and pressed play. No Music was playing.

**Comment by michaelherger** [comment] 2021-06-05 13:51
Have you tried re-authenticating the accounts after the addition of the client ID?

**Comment by AgentT-mo** [comment] 2021-06-05 14:04
I don't know if I tried this before I opened this Issue but I just tried.

When I start the process to authenticate the 2nd account using the "speaker-connect device"-method, a second Account gets added to the Spotty Plugin at the top, but I have no idea why it says the wrong name.
![screenshot accounts](https://user-images.githubusercontent.com/10178218/120894077-e9431580-c616-11eb-9272-a357d3d9a24b.PNG)
In the Spotify App the second Account is a different Logged in Account with a different name.
If i don't have the Client ID set, the second account states the correct name when authenticating this way.

<details>
      <summary>This is my Server Log now</summary>

![Screenshot ServerLog2](https://user-images.githubusercontent.com/10178218/120894210-99b11980-c617-11eb-8c24-6b615844dd12.png)
</details>

**Comment by michaelherger** [comment] 2021-06-07 03:46
Can you please double check the client ID is correct? Make sure there's no additional space at the head or tail of it or similar. And that you've gone through all the necessary steps required by Spotify to activate the ID.

I know that thousands of Spotty users use their own client ID by now. But this issue is new to me.

**Comment by AgentT-mo** [comment] 2021-06-07 13:59
Im sure the client ID is correct, since all the Error 429 log entries were gone when I were using my spotify account.
Never the less, I deleted the App with die Client ID on the Spotify Developer Page and created a new one with a new Client ID.
Double checked if there are now additional space at the start or end of the Client ID when setting the ID in the addon settings.

Result: 
It works on my Spotify Account, without any error messages in the log
On the second Account, I first tried it without authenticating in the plugin at first.
same behavior as before with `error 403: Forbidden`

Afterwards I tried authenticating the second Account. This time it states the correct name in the plugin page, but it still won't work and I get the same error messages as above.

Now I set the import Toggle of this Account to on, same behavior.

Finally I tried to completely reset the Spotify Android App. Tried directly after the login, tried with deleting the authentification, and tried after the authentification process. Issue remains with `error 403: Forbidden`.

Do I need so set anything special on the Spotify Developer Page?
In the Description on the settings page it states to create an App and follow the instructions there. And there I only have to click on next to get the Client ID. I have no Website, Redirect URIs, Bundle IDs and Android Packages.

**Comment by michaelherger** [comment] 2021-06-07 14:19
These are all premium accounts, right?

**Comment by AgentT-mo** [comment] 2021-06-07 14:29
Yes,
My Account is the Main Account of the family plan
Second Account is included in the family plan

I double checked that, at the Spotify profile page in the Premium Family category.
It asked me to set my address, which I did, but that didn't change anything regarding this issue.

**Comment by AgentT-mo** [comment] 2021-06-09 09:55
I've tried a few things without success. But I share my experience here, maybe it helps:

- Enabled the Spotify import Checkmark at the top of the plugins page of the second Account, and tried to play music through the LMS Webinterface and chose in the "Spotty Application" the second account.
-> Same behavior as before with the same error messages.
- Created a Spotify Developer Account (with accepting all the necessary Spotify Terms) on the second account.
-> Same behavior as before.  
- Tried to re-authenticate the second Account in the Plugin Settings
-> Same behaviour as before.

 - Created an App on the Spotify Developer page with the second Account, and used the Client ID of that App in the Spotty Plugin Page at the bottom
-> Spotify Connect now works on the second account without error messages. 
But it no longer works on the first Account, as I'm now getting the error messages when trying with this Account.
So also no success.

It seems like the Client IDs are somehow bound to the Account that created the App on the Spotify Developer Page.

Additional Info: 
My full setup consist of a Synology NAS with Docker.
LMS is installed there using the lmscommunity/logitechmediaserver:latest container.
The container are using the host network, so it shouldn't be a port issue.
As players I'm using two picoreplayer each on a Raspberry Pis.

My LMS is version 8.1.1 - 1610364019
Spotty plugin is version 4.4.9

Also, before I had only one speaker/pi and used hifiberry OS instead of picoreplayer. For the spotify integration it uses since version 20201101 [Vollibrespot](https://github.com/ashthespy/Vollibrespot) as mentioned [here.](https://github.com/hifiberry/hifiberry-os/blob/master/Changelog#L39)

With this installation I didn't have to create a Spotify developer App with an Client ID, and because there was no Client ID set it worked with both Accounts.

I then got a second Speaker that I wanted to sync, that's why I switched to LMS (after trying Snapcast)

For now I'm out of ideas, but will keep you updated, if new ideas I could try pop up.

**Comment by michaelherger** [comment] 2021-06-09 11:50
Can you check your client ID's "App Status" on the Spotify dashboard? They recently introduced dev mode etc. which seems to limit the possibilities, depending on the client ID's state. I'm wondering whether there's a limitation like one user only now. That would be bad :-(

**Comment by AgentT-mo** [comment] 2021-06-09 12:02
I don't see any App Status in the App View.
I see `the client ID `
the hidden `Client Secret`
as well as graphs for 
- Daily Active Users
- Monthly Active Users
- Users This Month (as a plain number)
- Number of Requests/Endpoint
- Number of Users Per Country (2021-06-08) (as a map)
- Total Number of Requests

Where exactly does it state the App Status?

**Comment by michaelherger** [comment] 2021-06-09 14:31
It's right above the Client ID line.

**Comment by AgentT-mo** [comment] 2021-06-09 14:37
It seems like this doesn't show with my account.
See below for a screenshot.
The App-Name `new LMS` and the description below that are the only things I see.

<details>
      <summary>Screenshot of Spotify Developer App</summary>
      
![image (11)](https://user-images.githubusercontent.com/10178218/121374783-7c928880-c940-11eb-9f3b-2327d67459a6.png)
</details>

**Comment by sirzandor** [comment] 2021-06-17 01:16
I have a similar issue with a second account.  My account works well... I can see all the devices and connect to them.  I added my wife's account successfully (see attached image) but she is unable to see any of the Spotty-related devices.  She can only see her own laptop, phone.   
![spotty](https://user-images.githubusercontent.com/86030836/122315343-313e3280-cf5d-11eb-9226-a2a98a39406e.jpg)

**Comment by michaelherger** [comment] 2021-06-17 03:39
@sirzandor this behavior is due to the "Don't announce SB players in your network" option. This would be checked automatically if Spotty failed too often. It could be a compatibility problem. Please do not continue discussion here, as this is a different problem.

**Comment by Deretour** [comment] 2021-06-17 15:54
I am quite sure to have ran into the same issue as my observations match the pattern described (most obvious similarities are **highlighted**).
Observations:
* Two Spotify accounts (sharing a Duo subscription)
* Created an "app" (for getting a token) on Spotify and entered it in Spottys settings
* First account (the one I created the App with) can use spotty normally
* Second account can briefly browse his Spotify library and soon after does not get any content anymore
* When reloading Spottys settings in LMS **second account is now renamed to the wrong name** (the one of the first account) but keeps its ID (checked in config file) and both accounts show up with the same name (but different IDs in the config file)
* For the second account the **same 403 API call errors are logged** in the log file
* **When deleting the app token in Spottys settings both accounts can use Spotty** and play their music but after a while we run into the 429 too many requests error and spotty stops working
* Also as @michaelherger **I do not see any App Status on the spotify developer dashboard**

Additional observation (not sure if related):
* When using the App token and playing from the Spotify app with the second account by selecting the network-player the app shows the song playing (time and slider progressing) but the player cannot play the music

I'm happy to provide further information if needed (nothing added yet as I think most essential information was already provided by @michaelherger)

**Comment by michaelherger** [comment] 2021-06-17 18:44
@Deretour - when did you create your client ID?

**Comment by Deretour** [comment] 2021-06-17 19:00
I cant tell exactly, but that was about one week ago

1. Signed up for Spotify about one and a half week ago and created my first account (directly with the duo subscription)
2. Installed and tested Spotty about one week ago with the fisrt account until I hit the 429 too many requests
3. Then (same day) I created the Client ID
4. Then we created the second account one day later I think and entered it as a second account in Spotty
5. As soon as the second account tried to browse Spotify through Spotty quickly after there was no content delivered
6. Headed to the Spotty settings to dicover the name of the second account had changed

Do you think the fact that we do not see an App Status and/or this issue in the dashboard could be related to the fact we signed up or registered the client ID recently whereas you did earlier?

**Comment by michaelherger** [comment] 2021-06-17 19:07
> Do you think the fact that we do not see an App Status in the dashboard and/or this issue could be related to the fact I signed up or registered the client ID recently whereas you did earlier?

I can't say (yet). I probably need to create another client ID to test this with, too. But a few weeks ago Spotify introduced some changes to how they handle client IDs. I wouldn't be surprised if that was causing the issues 😞 .

**Comment by michaelherger** [comment] 2021-06-17 19:31
Created a new config a few minutes and immediately got the status line:

<img width="523" alt="My Dashboard  Spotify for Developers" src="https://user-images.githubusercontent.com/2789989/122461010-18606c00-cfb3-11eb-9360-bba690f8bd72.png">
 Odd.

**Comment by Deretour** [comment] 2021-06-17 19:36
OK, App Status seems to be browser dependent.
I was using Firefox (with some privacy plug-ins) so far.
Just checked with Chrome and indeed now there is an app status.
It says "Development mode" (looks exactly like your screenshot.

**Comment by AgentT-mo** [comment] 2021-06-17 19:39
Strange, I just checked on Spotify Developer Page
With chrome no App Status is shown. With Edge it shows, just like your screenshot as well.

**Comment by Deretour** [comment] 2021-06-17 19:45
I just read what it says under the link in "(what does this mean?)"

If I understand correctly the quota should not be an issue in our case as it says up to 25 users should be able to use an application in Development mode.
Also the dashboard tells me that 2 Users were using the application recently.

Some further restrictions to "Development Mode" maybe?

**Comment by Deretour** [comment] 2021-06-17 19:54
Just saw now also the "Users and Access"  Button on the Spotify Dashboard (also not shown in FF for me)
Added the second account there.
But no luck so far. :(

**Comment by Deretour** [comment] 2021-06-17 20:04
Taking it back: I now it seems to work, had to restart the App on the phone of the second account.

So, solution seems to be to:
1. Find a browser that shows "App Status"
2. Go to "Users and Access"
3. Add the other account(s) that you want to allow using your instance ("Development Mode" limit is 25 Users)
4. *Just to be sure close your Spotify App and/or wait a little*

**Comment by AgentT-mo** [comment] 2021-06-17 20:16
I tried this approach.
After step 3
I deleted all authenticated Users in the Plugin.
And reauthenticated them. During this process a few Error 403 messages popped up in the log.

But the important part:

Spotify connect works fine!
(I haven't tried playing using the LMS UI)

Thank you very much!

**Comment by Deretour** [comment] 2021-06-17 20:21
Yes, not sure if this really all.
Had some issues but I was also changing the players setup at the same time, so could also be related to that.

I did not delete the authenticated users in the Plugin, just added the other account (the one that I did not create the Client ID with) on Spotify Dashboard.
But did not browse with the LMS UI in Spotify yet (that anyways is not a usecase I will use often, due to it's limited WAF ;) )

**Comment by michaelherger** [comment] 2021-06-17 20:49
Thank you very much, @Deretour! I was about to report that I was able to reproduce the issue, but didn't understand it yet. And here you are with the solution. Thanks again! I'll try to include this in the instructions for the custom client ID.

**Comment by Deretour** [comment] 2021-06-18 05:30
Thank you all, I think that was a collaborative effort: If @AgentT-mo wouldn't have had the same issue and asked I would have thought I was doing something wrong. And if @michaelherger wouldn't have supported us so well and pointed us towards the missing content on the dashboard we woudn't have found out.

Just for completeness it seems like the dasboard does not show all content for:
* FF (most recent version) under OSX (my case)
* Chrome under Windows (I guess @AgentT-mo case, correct me if this is wrong)

The dashboard seems to be rendered correctly for:
* Chrome (most recent version) under OSX (for me)
* Edge under Windows (for @AgentT-mo, again correctme if wrong)

From my perspective the issue can be closed.

**Closed** 2021-06-18 14:33 UTC

**Comment by jasell** [comment] 2021-06-20 19:39
> Taking it back: I now it seems to work, had to restart the App on the phone of the second account.
> 
> So, solution seems to be to:
> 
> 1. Find a browser that shows "App Status"
> 2. Go to "Users and Access"
> 3. Add the other account(s) that you want to allow using your instance ("Development Mode" limit is 25 Users)
> 4. _Just to be sure close your Spotify App and/or wait a little_

Hi, I have a problem understanding where you are when doing this.
I tried https://developer.spotify.com/dashboard/applications where I can see my app.
Entering the app I see App Status "Granted quota extension"
I have an entry for "Users and access" but that is inactive "can't be selected".
It says I can have unlimited number of users.
But
