### ISSUE TITLE
connect devices disappear from spotify app when starting group playback

### ISSUE THREAD

**Issue by daniel1v** [michaelherger/Spotty-Plugin#46] opened 2021-09-04 06:09 UTC
This is more a feature request, than a real issue:

I have two standalone players which are also part of a group. As soon as I start playback on the group player, both devices disappear from the Spotify Connect devices list. So it is impossible for me, to switch playback to one of these devices without switching to the web interface and unsyncing the from the group.

I think this behavior is intended, because the group player internally syncs the both standalone players, so the synced players are not broadcasted as connect players anymore, until they are unsynced. 

Maybe it would be possible to implement this as an optional feature: still broadcast the standalone players to spotify connect, even if they are synced to a group. If playback is started on one of these devices over Spotify Connect, stop group playback, unsync the device from the group and start playback on this device.

**Comment by sbrown7792** [comment] 2022-01-27 20:58
@daniel1v I see the same behavior. I can only add that if you pause the group player, wait ~30s or so, the individual players re-appear in the Spotify Connect device list. Might be easier for you than having to switch into the web interface. ✌

**Comment by electron23** [comment] 2022-07-13 15:28
+1

I'm getting the same issue

**Comment by giantorth** [comment] 2022-10-10 15:37
There is a workaround if you create single-speaker groups and only share those out, not the original speaker device.  Group speakers never stop getting shared regardless of where media is playing.

**Comment by michaelherger** [comment] 2023-11-14 12:15
Dupe of #34

**Closed by michaelherger** 2023-11-14 12:15 UTC
