### ISSUE TITLE
LMS stucks when adding second spotify family account

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [michaelherger/Spotty-Plugin#45] opened 2021-09-02 11:06 UTC
[_lms_logs (2).txt](https://github.com/michaelherger/Spotty-Plugin/files/7098393/_lms_logs.2.txt)
This is my container log.

The container I run is:
https://hub.docker.com/r/lmscommunity/logitechmediaserver

The first account was added previously. Sadly I am not able to give a server.log from lms, because lms is completely freezed.

**Comment by michaelherger** [comment] 2021-09-02 11:34
From the error message I'd say it's a temporary issue on Spotify's end. Can you try again in a bit and report back?

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-02 11:43
Its getting more clear.

It is no problem with a family-Account holder but with family-members within a spotify-family account.

**Comment by michaelherger** [comment] 2021-09-02 11:47
If you're using your own client ID (which you should be), then make sure you added those accounts to your client ID configuration (as outlined in the help text to the client ID setting).

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-02 11:54
I guess you mean this:
```
Spotify Client ID
Die Verwendung einer eigenen Client ID kann helfen, falls Sie Probleme mit dem "Rate Limiting" haben (Fehler 429). Um eine solche Client ID zu erhalten, befolgen Sie diese einfachen Schritte:
Besuchen Sie das Spotify Developer Portal, melden Sie sich falls nötig an.
Klicken Sie "Create An App", und folgen Sie den Anweisungen.
Kopieren Sie die neu erstellte Client ID, und fügen Sie sie in den Spotty Einstellungen ein.
Falls Sie einen Familienaccount verwenden, oder sonst mehrere Konten in Spotty verwenden möchten, fügen Sie die entsprechenden Konten bei der neu erstellten Konfiguration unter "Users and Access" hinzu.
```

**Comment by michaelherger** [comment] 2021-09-02 12:57
Yes.

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-02 13:07
okay, done. Add my main spotify family account with normal login creds and add the dev. client-id to the settings.

Within the sproitfy dev area I add the mail of the seconds family acc.

But how does this fix the login problem with a family account? I am not able to play a playlist from the 2nd account or?

**Comment by michaelherger** [comment] 2021-09-02 13:29
Do you still get the same failure?

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-02 14:11
Should I try now to add the seconds family acc?

**Comment by michaelherger** [comment] 2021-09-03 05:22
Hmm... how much time since your first failed attempt? Have you ever tried restarting your LMS machine?

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-03 06:24
Some minutes, but I did not track the time.

I really think this is some kind of Spotify family member api problem. Perhaps forced, I don't know.
I remember this issue here:
https://github.com/forslund/spotify-skill/issues/53

**Comment by michaelherger** [comment] 2021-09-03 07:01
We're using a family membership here, too. That's not the point. I believe it's a communication issue. The error in your log file says `AuthenticationError(LoginFailed(TryAnotherAP))`. Searching for similar errors I found references where Spotify would send a user to a different "access point" (AP), and librespot only seems to be handling one of them. Why you'd get this error, but "nobody" else, I don't know. That's why I thought a full reboot of your infrastructure, worst case up to the router, might help. I'm saying the router, as if they were blocking your IP or something, a router restart might get you a new address, freeing whatever lock there might be.

**Comment by sorryusernameisalreadytaken** [comment] 2021-09-03 07:55
I got it :D

It was the password. It contained a **$**. I replaced it with a **-**.

Can you reproduce this?

**Comment by michaelherger** [comment] 2021-09-03 11:25
Wow... that's rather surprising. Now I have to figure out whether this is an issue in the way I pass the password to the helper, or with the helper itself. Because I thought I had addressed the $ sign issue before. What OS are you using?

**Comment by michaelherger** [comment] 2023-11-14 12:23
dupe of #79

**Closed by michaelherger** 2023-11-14 12:23 UTC
