### ISSUE TITLE
Spotify Connect: Player stops after two songs

### ISSUE THREAD

**Issue by mr-manuel** [michaelherger/Spotty-Plugin#69] opened 2022-07-23 20:52 UTC
Hello,

I have the problem, that when I use the Spotify App with Spotify Connect the playback stops after exactly two songs. It doesn't matter which room I select or if the players are synced or not. It also doesn't matter, if I use the Android, iOS, Windows or web app of Spotify. It also makes no difference, if I start a single song or a whole playlist in the Spotify app. When I select a song from LMS -> My Apps -> Spotty it works without problem.

I enabled debugging of Spotty but found nothing helpful. I also reinstalled LMS and the players (max2play) from scratch, but no change.

In the difference to https://github.com/michaelherger/Spotty-Plugin/issues/14 the player is not disconnected. The song stops at the end (screenshot 1) or sometimes even exeeds the song time (screenshot 2) and the next song is not loaded. Pressing play also do not work. I have to select a new song, then it works again for two songs. So it's a mix of issue https://github.com/michaelherger/Spotty-Plugin/issues/14 and https://github.com/michaelherger/Spotty-Plugin/issues/49.

I have also another setup at a friends place (LMS + max2play + Spotty) with the same issue.

Let me know, if you need further details.

<details>
<summary>Spotty settings</summary>

![grafik](https://user-images.githubusercontent.com/12592765/180622233-3a78a42a-61d5-4d64-a181-8d6345a01d6f.png)

</details>

<details>
<summary>Screenshot 1</summary>

![Screenshot_20220723-214200_Spotify](https://user-images.githubusercontent.com/12592765/180621992-a9b3dee2-ce13-444c-a9f0-f3d699cf1f1d.jpg)

</details>

<details>
<summary>Screenshot 2</summary>

![Screenshot_20220723-214215_Spotify](https://user-images.githubusercontent.com/12592765/180621998-34321cdc-ece7-455c-8687-f8892b6f44cb.jpg)

</details>

Since the log is to long I had to attach it: [server.log](https://github.com/michaelherger/Spotty-Plugin/files/9174623/server.log)

**Comment by bungh0l10** [comment] 2022-07-25 06:18
I encounter similar issues and found an odd string `access-control-max-age" => 604_800` while debugging Slim::Networking::Async::HTTP ,  see [here](https://forums.slimdevices.com/showthread.php?111923-Announce-Spotty-4-0-integrate-local-library-with-your-Spotify-collection-(LMS-8-)&p=1058321&viewfull=1#post1058321)

**Comment by michaelherger** [comment] 2022-07-25 13:35
Please disable the top three "Advanced Settings" in your screenshot. In particular the first one ("Optimise Pre-Buffering") can cause more harm then it helps. Then try again and report back.

As for the underscore in numbers (`604_800`), that's a Perl thing to make numbers easily readable (see eg. https://www.perlmonks.org/?node_id=72112).

**Comment by mr-manuel** [comment] 2022-07-26 11:19
Now I disabled all top tree options but unfortunately no change.

**Comment by jockef3000** [comment] 2022-07-26 14:47
I have the same problem. I can play one song on my spotify playlist using spotify connect from my phone. After the song is played it stops. I also have problems with having to try starting a song several times before it starts.

Im using LMS in docker and Hifiberry running on RPI2. From what I can remember this used to work a couple of weeks ago.

Looking at the debug log I can see the song playing and after the song It looks like its trying to start the next song.

  $a->{device}{is_active} = \${$a->{actions}{disallows}{"toggling_repeat_track"}};
  $a->{device}{is_restricted} = \${$a->{device}{is_private_session}};
  $a->{is_playing} = \${$a->{actions}{disallows}{"toggling_repeat_track"}};
  $a->{item}{explicit} = \${$a->{actions}{disallows}{"toggling_repeat_track"}};
  $a->{item}{is_playable} = \${$a->{actions}{disallows}{"toggling_repeat_track"}};
  $a->{shuffle_state} = \${$a->{device}{is_private_session}};
  ($a, "stop");

**Comment by michaelherger** [comment] 2022-07-26 14:56
Could you please share the full log file, with a hint about when playback stopped? INFO level should be good enough, as DEBUG is super noisy...

**Comment by bungh0l10** [comment] 2022-07-27 10:14
Hi Michael,

I tried to be precise while writing down what I did on mobile and what happened on the SB using connect mode. Maybe it helps.
[serverlog.txt](https://github.com/michaelherger/Spotty-Plugin/files/9197341/serverlog.txt)
[steps.txt](https://github.com/michaelherger/Spotty-Plugin/files/9197342/steps.txt)

PS: Thanks for the Perl  numbers explanation :)

**Comment by michaelherger** [comment] 2022-07-27 13:02
Are you sure no other device is using your Spotify account at the same time? I'm seeing that Spotty is told (by Spotify) to end playback. This would often happen if somebody else in the same household (or in the office) sharing your account would use the service.

**Comment by bungh0l10** [comment] 2022-07-27 14:57
Hi Michael,

I made this walkhrough at my garden place where nobody else was accessing the local network same time. While I have a granted quota extension on my account (dev client id) I haven't shared my account credentials somewhere else because each family member has his/her own account (premium family) and was at work/school at that time and not using apotify at all. I'll try to engage spotify support to check my account though and update here in case there is / was something wrong.

**Comment by jockef3000** [comment] 2022-07-29 07:16
> I have the same problem. I can play one song on my spotify playlist using spotify connect from my phone. After the song is played it stops. I also have problems with having to try starting a song several times before it starts.
> 
> Im using LMS in docker and Hifiberry running on RPI2. From what I can remember this used to work a couple of weeks ago.
> 
> Looking at the debug log I can see the song playing and after the song It looks like its trying to start the next song.

I have tried to reproduce the problem but now it seems to be working alright. I suspect I had spotify running on another client that maybe caused my problem. Thanks!

**Comment by myde2001** [comment] 2022-09-11 12:36
The same is happening to me

**Comment by michaelherger** [comment] 2023-11-14 12:16
Likely a dupe of #82.

**Closed by michaelherger** 2023-11-14 12:16 UTC
