### ISSUE TITLE
Spotify connect not working as well as every spotify:// link

### ISSUE THREAD

**Issue by loadamasta** [michaelherger/Spotty-Plugin#133] opened 2024-08-12 14:27 UTC
Since a couple of days, the spotty plugin is not working anymore. Worked for months on that system without any issue. This is the error:

Beim Ausführen der Spotty Helfer-Anwendung ist ein Fehler aufgetreten. Vermutlich wird diese auf ihrem System nicht unterstützt. Bitte wenden Sie sich an mich, unter Angabe der folgenden Plattform-Informationen:

Betriebssystem: Debian (Docker Home Assistant Addon) / x86_64-linux

Ordner für Hilfsprogramme:
/usr/share/squeezeboxserver/Bin/x86_64-linux
/usr/share/squeezeboxserver/Bin
/command
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/libexec
/config/lms/cache/InstalledPlugins/Plugins/RaopBridge/Bin
/config/lms/cache/InstalledPlugins/Plugins/ShairTunes2W/Bin
/config/lms/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux
/config/lms/cache/InstalledPlugins/Plugins/Spotty/Bin
/config/lms/cache/InstalledPlugins/Plugins/UPnPBridge/Bin
ldd (Debian GLIBC 2.36-9+deb12u7) 2.36

**Comment by michaelherger** [comment] 2024-08-12 14:39
This error suggests that your system can't find the spotty helper application, or that it didn't work any more for whatever reason.

You mention Home Assistant and that it used to work before? I wonder whether the latest HA update was causing an issue? Did you try to re-install the plugin, in case something had messed up permissions or similar?

**Comment by michaelherger** [comment] 2024-09-11 04:02
Closing as dupe of #140

**Closed by michaelherger** 2024-09-11 04:02 UTC
